DFE-Digital/get-information-about-schools

Web/Edubase.Web.UI/Areas/Establishments/Views/BulkAssociateEstabs2Groups/BulkAssociateEstabs2Groups.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/BulkUpdate/InProgress.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/BulkUpdate/Index.cshtml, Web/Edubase.Web.UI/Areas/Governors/Views/GovernorsBulkUpdate/Index.cshtml, Web/Edubase.Web.UI/Views/Tools/MergersTool.cshtml
Should address the bugs in the four defects specified in title.
=> Commit to address defects 45595/6/7/8

Web/Edubase.Web.UI/Areas/Establishments/Views/BulkUpdate/InProgress.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/BulkUpdate/Index.cshtml
=> Further bugfixes to 45596

Web/Edubase.Web.UI/Views/Tools/MergersTool.cshtml
Remembered to switch to dev this time.  5 edits, alma*=>amal*.
=> Edits for typoes

Web/Edubase.Web.UI/Views/Home/Contact.cshtml
A couple of edits as advised by Mattias
=> Updates as per QA comments

Web/Edubase.Web.UI/Views/Home/News.cshtml
As per Claire's comments, a couple of minor display changes
=> Changes as per CF comments

Web/Edubase.Web.UI/Assets/Scripts/Entry/bundle.js
Should be OK, but NPM has been giving some unusual error messages so I'd appreciate this being given a once-over.  Thanks, Sean
=> 46357-update-modal-news-dialog

Web/Edubase.Web.UI/Views/Guidance/Federation.cshtml
Fix of incorrectly encoded smart quotes (~40)
=> Updated smart quotes to entity references

Web/Edubase.Web.UI/Views/Home/Help.cshtml
Reverts DFE-Digital/get-information-about-schools#43
=> Revert "Revised display order"

Web/Edubase.Web.UI/Views/Faq/Index.cshtml
=> 46356 Typo fixed

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Details.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Index.cshtml, Web/Edubase.Web.UI/Areas/Governors/Views/GovernorSearch/Index.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Details.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/GroupSearch/GroupResults.cshtml
Still a large number of mods in group details file - the only change was from section backlink to breadcrumb.  Windiff suggests that yes, these are just whitespace changes.
=> 44167 - redo of breadcrumb changes incorporating recent updates

Web/Edubase.Web.UI/Views/Search/LocalAuthorityDisambiguation.cshtml, Web/Edubase.Web.UI/Views/Search/LocationDisambiguation.cshtml
Mattias added a couple of pages to 44167 that had been missed from the ACs.  This should address these.
=> 46900 interstitial pages

Web/Edubase.Web.UI/Areas/Groups/Views/Group/Details.cshtml
44167-change of text as per Osman/Kevin's comments.
=> 46938-correction-to-copy

Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Downloads/SelectCustomFields.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Downloads/SelectDataset.cshtml, Web/Edubase.Web.UI/Areas/Governors/Views/GovernorSearch/Downloads/SelectDataset.cshtml, Web/Edubase.Web.UI/Views/Shared/Downloads/ReadyToDownload.cshtml
44167:related - made changes to four additional pages in line with the intent.
=> Updates, removing 'back to search results' x 4

Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Downloads/SelectCustomFields.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Downloads/SelectDataset.cshtml, Web/Edubase.Web.UI/Areas/Governors/Views/GovernorSearch/Downloads/SelectDataset.cshtml, Web/Edubase.Web.UI/Views/Shared/Downloads/DownloadError.cshtml, Web/Edubase.Web.UI/Views/Shared/Downloads/PreparingFilePleaseWait.cshtml, Web/Edubase.Web.UI/Views/Shared/Downloads/ReadyToDownload.cshtml, Web/Edubase.Web.UI/Views/Shared/Downloads/SelectFormat.cshtml
46937/47177 - amendment to breadcrumb navigation
=> Amendment to breadcrumbs (7 files)

Web/Edubase.Web.UI/403.aspx, Web/Edubase.Web.UI/403.html, Web/Edubase.Web.UI/404.aspx, Web/Edubase.Web.UI/404.html, Web/Edubase.Web.UI/500.aspx, Web/Edubase.Web.UI/500.html, Web/Edubase.Web.UI/App_offline_x.htm
47041/47178 - updates to survey links on static pages
=> Updates to static survey links

Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Downloads/SelectCustomFields.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Downloads/SelectDataset.cshtml
Change as two of the backlinks didn't work correctly on dev.
=> 47228 - fixing error reported by Mattias on the two interstitial pages

Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Downloads/SelectCustomFields.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Downloads/SelectDataset.cshtml, Web/Edubase.Web.UI/Areas/Governors/Views/GovernorSearch/Downloads/SelectDataset.cshtml, Web/Edubase.Web.UI/Views/Shared/Downloads/DownloadError.cshtml, Web/Edubase.Web.UI/Views/Shared/Downloads/ReadyToDownload.cshtml, Web/Edubase.Web.UI/Views/Shared/Downloads/SelectFormat.cshtml
Six files: 2 x interstitials for Establishment route; 1 for governors non-public data, 3 general downloads dialogues.
=> 47228-changes-to-breadcrumbs-reapplying

Web/Edubase.Web.UI/Views/Shared/Downloads/PreparingFilePleaseWait.cshtml
Mattias pointed out one of the interstitial pages had been missed; this fixes (one file)
=> 47228-additional-interstitional-page-missed

Web/Edubase.Web.UI/403.aspx, Web/Edubase.Web.UI/403.html, Web/Edubase.Web.UI/404.aspx, Web/Edubase.Web.UI/404.html, Web/Edubase.Web.UI/500.aspx, Web/Edubase.Web.UI/500.html, Web/Edubase.Web.UI/Views/GOVUK/Layouts/template.cshtml
Redone.  Used actionlink for main template (was looking at controller incorrectly) also disabled format changes and left contact link alone.
=> 47417/47656 - redo with formatting changes disabled.

Web/Edubase.Web.UI/Views/Home/Help.cshtml
Added link to accessibility statement to help page.
=> 47832-47412-adding-accessibility-link-to-Help-page

Web/Edubase.Web.UI/403.aspx, Web/Edubase.Web.UI/403.html, Web/Edubase.Web.UI/404.aspx, Web/Edubase.Web.UI/404.html, Web/Edubase.Web.UI/500.aspx, Web/Edubase.Web.UI/500.html, Web/Edubase.Web.UI/Views/GOVUK/Layouts/template.cshtml
Note, this deviates slightly from the original acceptance criteria. [1] There was no consideration of the "Privacy" item in the original ACs, this has been added.  [2] There slight discrepancies with the static pages, these have been reconciled.
=> 47831-updates-all-consistent-as-per-amendments-on-47414.

Web/Edubase.Web.UI/Views/Search/LocalAuthorityDisambiguation.cshtml, Web/Edubase.Web.UI/Views/Search/LocationDisambiguation.cshtml
To address bug 48049 - changed backlinks to breadcrumbs on two interstitial pages
=> 47458-interstitial-pages

Web/Edubase.Web.UI/Areas/Establishments/Controllers/EstablishmentController.cs, Web/Edubase.Web.UI/Areas/Establishments/Models/CreateEstablishmentViewModel.cs, Web/Edubase.Web.UI/Areas/Establishments/Models/Validators/CreateEstablishmentViewModelValidator.cs, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Create.cshtml
Think I've finally got it.  Grateful if you could take a look and critique.
=> 44445 non js journey

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Create.cshtml
Brief update to add early cancel buttons to pages.  One file / two lines added.
=> Minor amendment, added cancel buttons to early stages of journey

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Details.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/TabDetails.cshtml
Added new tooltip for %
Changed wording old existing tooltip
=> 49370 - amended fsm tooltip and added fsm percentage tooltip

Web/Edubase.Web.UI/Areas/Establishments/Controllers/EstablishmentController.cs, Web/Edubase.Web.UI/Areas/Establishments/Models/CreateEstablishmentViewModel.cs, Web/Edubase.Web.UI/Areas/Establishments/Models/Validators/CreateEstablishmentViewModelValidator.cs, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Create.cshtml
removed cancel buttons
combined estab number steps into single step
added code to catch validation errors on final step and allow user to navigate back
=> 49045 back links bugs

Web/Edubase.Web.UI/Areas/Governors/Views/Governor/ViewEdit.cshtml
Matches the pics sent round on Wednesday.
=> Edits as discussed and screenshotted in story 48096

Web/Edubase.Web.UI/Views/GOVUK/Layouts/template.cshtml
Quick change to address newly created bug 50913
=> Bugfix: change CSS class on terms of use link

Web/Edubase.Web.UI/Views/Home/Responsibilities.cshtml
OK, both changes definitely showing now.
=> 50624 academy trust handbook

Web/Edubase.Web.UI/Views/TermsofUse/Index.cshtml
Fixes for bugs 50935 and 50937 raised during QA
=> Bugfixes 50935 / 50937

Web/Edubase.Web.UI/Views/GOVUK/Layouts/template.cshtml, Web/Edubase.Web.UI/Views/Home/Help.cshtml, Web/Edubase.Web.UI/Views/TermsofUse/Index.cshtml
Capitalisation amended on three pages to address bugs 50979/80/81
=> Changes to capitalisation, three files

Web/Edubase.Web.UI/Areas/Establishments/Controllers/AcademyOpeningsController.cs, Web/Edubase.Web.UI/Areas/Establishments/Controllers/BulkAssociateEstabs2GroupsController.cs, Web/Edubase.Web.UI/Areas/Establishments/Controllers/BulkCreateFreeSchoolsController.cs, Web/Edubase.Web.UI/Areas/Establishments/Controllers/BulkUpdateController.cs, Web/Edubase.Web.UI/Areas/Establishments/Controllers/EstablishmentController.cs, Web/Edubase.Web.UI/Areas/Establishments/Controllers/EstablishmentsSearchController.cs, Web/Edubase.Web.UI/Areas/Groups/Controllers/GroupApiController.cs, Web/Edubase.Web.UI/Areas/Groups/Controllers/GroupController.cs, Web/Edubase.Web.UI/Controllers/AccountController.cs, Web/Edubase.Web.UI/Controllers/SitemapController.cs, Web/Edubase.Web.UI/Global.asax.cs, Web/Edubase.Web.UI/Helpers/HtmlHelperExtensions.cs, Web/Edubase.Web.UI/Helpers/JsonCamelCaseResult.cs, Web/Edubase.Web.UI/Helpers/LangExt.cs, Web/Edubase.Web.UI/Helpers/LayoutHelper.cs, Web/Edubase.Web.UI/Helpers/RoleEquivalence.cs, Web/Edubase.Web.UI/Helpers/UrlHelperExtensions.cs, Web/Edubase.Web.UI/Helpers/ValidationExtensions.cs, Web/Edubase.Web.UI/Models/Grid/GridRowViewModel.cs, Web/Edubase.Web.UI/Models/Grid/GridViewModel.cs, Web/Edubase.Web.UI/Models/ToolsViewModel.cs, Web/Edubase.Web.UI/ValueConverters/WeblinkConverter.cs
PR for sean's code cleanup work which was completed before he left the team
=> 50809 for consideration

Web/Edubase.Services.Texuna/Approvals/ApprovalService.cs, Web/Edubase.Services.Texuna/Lookup/LookupApiService.cs, Web/Edubase.Services.TexunaUnitTests/Approvals/ApprovalServiceTests.cs, Web/Edubase.Services.TexunaUnitTests/Edubase.Services.TexunaUnitTests.csproj, Web/Edubase.Services.TexunaUnitTests/Lookup/LookupApiServiceTests.cs, Web/Edubase.Services/Lookup/CachedLookupService.cs
Edubase.Services.Texuna.Approvals - Changed to use HttpClient Interface and changed formatting of code
Added ApprovalServiceTests.cs
=> Unit tests written for Approval Service

Web/Edubase.Web.UI/Web.config
The formatting was corrected, but thge main code change is line is lines 298 to 305
=> Fixed header processing

Web/Edubase.Web.UI/Models/ToolsViewModel.cs, Web/Edubase.Web.UI/Views/Notifications/Index.cshtml
Removed banner archive UI updates
=> Removed banner archive UI updates

Web/Edubase.Web.UI/Views/Search/Partials/_HelpText.cshtml
=> removed colon after UKPRN

Web/Edubase.Web.UI/Web.Release.config, Web/Edubase.Web.UI/Web.config, Web/Edubase.Web.UI/package-lock.json
also removed the existing line in the Web.Release.Config, as it would conflict with the new line in Web.Config
=> Updated web.config to add http only cookies

Web/Edubase.Web.UI/Assets/Sass/GiasSearchResults/_download-search-results.scss
Updated padding to 10px match Story requirements
=> Updated to 10px to match Story requirements

Web/Edubase.Web.UI/Areas/Governors/Views/Governor/AddEditOrReplace.cshtml, Web/Edubase.Web.UI/Areas/Governors/Views/Governor/ReplaceChair.cshtml
Added missing breadcrumbs for edit establishment governor -> Edit person and remove person
=> Added missing breadcrumbs

Web/Edubase.Services.Texuna/Edubase.Services.Texuna.csproj, Web/Edubase.Services.Texuna/packages.config, Web/Edubase.Services.TexunaUnitTests/app.config, Web/Edubase.UnitTest/app.config, Web/Edubase.Web.ResourcesUnitTests/Edubase.Web.ResourcesUnitTests.csproj, Web/Edubase.Web.UI/Edubase.Web.UI.csproj, Web/Edubase.Web.UI/Web.config, Web/Edubase.Web.UI/packages.config, Web/Edubase.Web.UIUnitTests/Edubase.Web.UIUnitTests.csproj
Reverting _Microsoft.AspNet.WebApi.Client_ from 5.2.9.0 to 5.2.3.0
=> Reverting Microsoft.AspNet.WebApi.Client from 5.2.9.0 to 5.2.3.0

Web/Edubase.Services.Texuna/Edubase.Services.Texuna.csproj, Web/Edubase.Services.Texuna/packages.config, Web/Edubase.Services.TexunaUnitTests/app.config, Web/Edubase.UnitTest/app.config, Web/Edubase.Web.ResourcesUnitTests/Edubase.Web.ResourcesUnitTests.csproj, Web/Edubase.Web.UI/Edubase.Web.UI.csproj, Web/Edubase.Web.UI/Web.config, Web/Edubase.Web.UI/packages.config, Web/Edubase.Web.UIUnitTests/Edubase.Web.UIUnitTests.csproj
Reverts DFE-Digital/get-information-about-schools#200
=> Revert "Reverting Microsoft.AspNet.WebApi.Client from 5.2.9.0 to 5.2.3.0"

Web/Edubase.Common/Edubase.Common.csproj, Web/Edubase.Common/app.config, Web/Edubase.Common/packages.config, Web/Edubase.CommonUnitTests/Edubase.CommonUnitTests.csproj, Web/Edubase.Data/App.config, Web/Edubase.Data/Edubase.Data.csproj, Web/Edubase.Data/packages.config, Web/Edubase.DataUnitTests/Edubase.DataUnitTests.csproj, Web/Edubase.Services.Texuna/app.config, Web/Edubase.Services.TexunaUnitTests/Edubase.Services.TexunaUnitTests.csproj, Web/Edubase.Services.TexunaUnitTests/app.config, Web/Edubase.Services.TexunaUnitTests/packages.config, Web/Edubase.Services/App.config, Web/Edubase.Services/Edubase.Services.csproj, Web/Edubase.Services/packages.config, Web/Edubase.ServicesUnitTests/Edubase.ServicesUnitTests.csproj, Web/Edubase.UnitTest/Edubase.UnitTest.csproj, Web/Edubase.UnitTest/app.config, Web/Edubase.UnitTest/packages.config, Web/Edubase.Web.Resources/app.config, Web/Edubase.Web.ResourcesUnitTests/Edubase.Web.ResourcesUnitTests.csproj, Web/Edubase.Web.UI/ApplicationInsights.config, Web/Edubase.Web.UI/Edubase.Web.UI.csproj, Web/Edubase.Web.UI/Web.config, Web/Edubase.Web.UI/packages.config, Web/Edubase.Web.UIUnitTests/Edubase.Web.UIUnitTests.csproj
Packages not updated in this PR
Autofac.WebApi2
Automapper
FluentValidation
Microsoft.AspNet.WebApi.Client
Polly
StackExchange.Redis
System.Diagnostics.DiagnosticSource
System.Management
System.Memory
=> NuGet Package Updates

Web/.filenesting.json, Web/Edubase.Common/Edubase.Common.csproj, Web/Edubase.Common/app.config, Web/Edubase.Common/packages.config, Web/Edubase.Data/App.config, Web/Edubase.Services.Texuna/app.config, Web/Edubase.Services.TexunaUnitTests/app.config, Web/Edubase.Services/App.config, Web/Edubase.UnitTest/Edubase.UnitTest.csproj, Web/Edubase.UnitTest/app.config, Web/Edubase.UnitTest/packages.config, Web/Edubase.Web.Resources/app.config, Web/Edubase.Web.ResourcesUnitTests/Edubase.Web.ResourcesUnitTests.csproj, Web/Edubase.Web.UI/Edubase.Web.UI.csproj, Web/Edubase.Web.UI/Web.config, Web/Edubase.Web.UI/packages.config, Web/Edubase.Web.UIUnitTests/Edubase.Web.UIUnitTests.csproj
Second update of solution NuGet packages
The following packages have not been updated and will be addressed in future stories
- Automapper
- FluentValidation
- Polly
- StackExchange.Redis
=> Updated NuGet Packages

Web/Edubase.Web.UI/Areas/Establishments/Views/AcademyOpenings/Index.cshtml, Web/Edubase.Web.UI/Views/Approvals/Index.cshtml
Added to the following pages:
Manage academy openings page (need to be signed in)
(https://get-information-schools.service.gov.uk/Establishments/manage/academy-openings#calendar)
Manage change requests (need to be signed in)
(https://get-information-schools.service.gov.uk/Approvals)
=> Added missing chevrons

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/EditDetails.cshtml
Adding in button locator to assist with the writing of the test framework
=> 1932941 - Adding in Test Locators for ASConfirm Button

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/EditDetails.cshtml
Reverts DFE-Digital/get-information-about-schools#241
=> Revert "1932941 - Adding in Test Locators for ASConfirm Button"

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/EditDetails.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/EditLocation.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/TabLocation.cshtml
Further ids added for lookup tests.
=> further ids add for lookup tests

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/EditIEBT.cshtml, Web/Edubase.Web.UI/Helpers/HtmlHelperExtensions.cs
Adding in a new helper to add id's to option choices in select drop down
=> 133514 - Select / Drop Down Helper

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/ConfirmationNotifications.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/TabDetails.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/CreateAcademyTrust.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Details.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Partials/Details/_GenericGroupDetails.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/SearchCompaniesHouse.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/_EditLayoutPage.cshtml, Web/Edubase.Web.UI/Views/GOVUK/Layouts/template.cshtml, Web/Edubase.Web.UI/Views/Tools/Index.cshtml
locators added for create academy trust tests in s158-web-test-automation
=> locators added for create academy trust tests

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Create.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Details.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/EditHelpdesk.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/EditIEBT.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/EditLinks.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/EditLocation.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/TabDetails.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/TabGovernance.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/_EditLayoutPage.cshtml, Web/Edubase.Web.UI/Areas/Governors/Views/Governance/EditGovernanceMode.cshtml, Web/Edubase.Web.UI/Areas/Governors/Views/Governor/ViewEdit.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Details.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/_EditLayoutPage.cshtml
further ids added for establishment group tests
=> id locators added for automated establishment group tests

Web/Edubase.Web.UI/Areas/Establishments/Views/AcademyOpenings/Index.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/AcademyOpenings/SearchAcademyOpenings.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/GovernanceChangeHistory.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/_EditLayoutPage.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Details.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/GovernanceChangeHistory.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/_EditLayoutPage.cshtml, Web/Edubase.Web.UI/Views/Downloads/Index.cshtml
added tab wrap id as the previous one is not worked
=> added id="tab-wrap"

Web/Edubase.Web.Resources/ApiMessages.resx
Override error message when setting an appointment date in the future to be descriptive
#138965
---
**Before -** 
---
**After -**
=> Override error message when setting an appointment date in the future

Web/Edubase.Web.UI/Areas/Establishments/Views/AcademyOpenings/Index.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/BulkAssociateEstabs2Groups/BulkAssociateEstabs2Groups.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/AddEditLink.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/AddEditLink_FindEstablishment.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Create.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/EditDetails.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/Header.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/TabLinks.cshtml, Web/Edubase.Web.UI/Areas/Governors/Views/GovernanceDelegation/GroupEditDelegation.cshtml, Web/Edubase.Web.UI/Areas/Governors/Views/Governor/ReplaceChair.cshtml, Web/Edubase.Web.UI/Areas/Governors/Views/GroupCorporateContact/GroupEditCorporateContact.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/EditLinks.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Partials/Details/_GenericGroupDetails.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Warnings.cshtml, Web/Edubase.Web.UI/Views/Approvals/Index.cshtml, Web/Edubase.Web.UI/Views/ChangeHistory/Download.cshtml, Web/Edubase.Web.UI/Views/Tools/MergersTool.cshtml, Web/Edubase.Web.UI/package-lock.json
Added ids related to amalgamation and federation group
=> Federation amalgamation

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Details.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Details.cshtml
=> Academic sponsor group

Web/Edubase.Web.UI/Views/Guidance/EstablishmentBulkUpdate.cshtml
- renaming LA (Name), and removing LA Code. Also applied lint/reformat of the file
=> Updated bulk update guidance to use just LA 

Web/Edubase.Services.Texuna/Lookup/LookupApiService.cs
added hard coded EstablishmentType to EstablishmentTypeGroup
=> 141693 add new establishment types

Web/Edubase.Web.UI/Views/Shared/EditorTemplates/GovernorViewModel.cshtml
Another locator train for you all. I thought I had added these ones in but apparently not
Again a single file with a few ID's added to make life easier for the test suite
=> Additional ID locators to match the test suite requirements

Web/Edubase.Web.UI/Areas/Governors/Views/Governor/ViewEdit.cshtml
Accidentally broke a radio button so this is the fix for it
=> TEST-ID: Radio Aria-Control Fix

Web/Edubase.Web.UI/Views/Shared/EditorTemplates/GovernorViewModel.cshtml
Change to sort merge conflict problem
=> Initial commit

Web/Edubase.Web.UI/Areas/Governors/Views/Governor/ViewEdit.cshtml
Updating the page locators (not the input this time) so it can be used for testing purposes
=> Locator Updates

Web/Edubase.Web.UI/Areas/Governors/Views/GovernorsBulkUpdate/Index.cshtml
Wording updated - Template in correct place after checking DAzure and opening in all environments
=> Innitial commit

Web/Edubase.Web.UI/Areas/Groups/Models/Validators/GroupEditorViewModelValidator.cs
=> Add validation check to ensure that only variations of a children's centre establishment, may be added to a children's centres group

Web/Edubase.Web.UI/Models/EstablishmentDetailViewModel.cs
=> Display the county and country only where it is supplied. Also only display the country if it is outside of the UK

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Details.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Details.cshtml, Web/Edubase.Web.UI/Helpers/StringUtils.cs, Web/Edubase.Web.UI/Views/Downloads/Download.cshtml, Web/Edubase.Web.UI/Views/Downloads/Index.cshtml, Web/Edubase.Web.UI/Views/Downloads/Partials/_DownloadsResults.cshtml, Web/Edubase.Web.UI/Views/Downloads/PreparingFilePleaseWait.cshtml, Web/Edubase.Web.UI/Views/Downloads/ReadyToDownload.cshtml, Web/Edubase.Web.UI/Views/Downloads/SelectFormat.cshtml, Web/Edubase.Web.UI/Views/Shared/EditorTemplates/DateTimeViewModel.cshtml
ids added for all download pages
=> ids added for download pages

Web/Edubase.Web.UI/Areas/Governors/Views/GovernorsBulkUpdate/Index.cshtml
Reverts DFE-Digital/get-information-about-schools#343 - this is per the update on task: bug - 146997 that has been re-opened, the file is where it should be and opens but the wording needs to be changed back to how it was originally - GovernanceTemplate.xlsx, 18KB
=> Revert "Initial commit"

Web/Edubase.Web.UI/App_Start/IocConfig.cs, Web/Edubase.Web.UI/Web.Release.config, Web/Edubase.Web.UI/Web.config, Web/Edubase.Web.UIUnitTests/App_Start/IocConfigTests.cs, Web/Edubase.Web.UIUnitTests/Edubase.Web.UIUnitTests.csproj
Changed the configuration of the lookup client to be more explicit the config - added unit tests for method
=> Changed the configuration of the lookup client to be more explicit on the config

Web/Edubase.Web.UI/Areas/Establishments/Controllers/EstablishmentController.cs, Web/Edubase.Web.UI/Areas/Establishments/Models/TabWarningsModel.cs, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/TabDetails.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/TabLocation.cshtml, Web/Edubase.Web.UI/Edubase.Web.UI.csproj, Web/Edubase.Web.UI/Models/EstablishmentDetailViewModel.cs, Web/Edubase.Web.UIUnitTests/Areas/Establishments/Models/TabWarningsModelTests.cs
Add warning message to establishment view details and location tabs when establishment type is 'academy 16-19 secure'
strory https://dfe-ssp.visualstudio.com/s158-Get-Information-About-Schools/_workitems/edit/142579
=> 16 19 secure/142579 warning message re care of address

Web/Edubase.Web.UI/Areas/Groups/Views/Group/Create.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/EditLinks.cshtml
Steps:
On your local machine, please follow the steps as addressed on the ticket:
=> 132810 - Implement modal on Federation creation

Web/Edubase.Web.UI/Areas/Groups/Controllers/GroupController.cs, Web/Edubase.Web.UI/Areas/Groups/Views/Group/EditDetails.cshtml
Steps:
On your local machine, please follow the steps as addressed on the ticket/story:
=> 147382 Bugfix: Disabled input allows updates

Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Partials/_EstablishmentSearchResults.cshtml
see bug for full details (long)
=> added null conditional operator to stop null exception for ycs user

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Details.cshtml, Web/Edubase.Web.UI/Models/EstablishmentDetailViewModel.cs
The existing informational message will has been amended to remove the line and hyperlink View details of linked establishment as Academies secure 16-19 do not have linked establishment
=> BG/164258_Establishment_Closed_Message (166291 sub task)

.github/workflows/build-and-test.yml, .github/workflows/build.yml
This GitHub Action will build the project and run unit tests as part of the PR and merge into dev/master branch processes.
=> Initial build and test workflow

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/TabLocation.cshtml
Region editable by BO.
Change in code to re-position field to meet AC
=> BG/164244 - Regional schools commissioner (RSC)

Web/Edubase.Web.UI/Areas/Governors/Views/GovernorSearch/Partials/_GovernorSearchResults.cshtml
removed extra class in closing tag
=> fixed bad closing tag

Web/Edubase.Web.UI/Helpers/AuthorizedRoles.cs
Updated authorised roles for YCS and SSAT Roles
https://dev.azure.com/dfe-ssp/s158-Get-Information-About-Schools/_workitems/edit/171959
GIVEN I'm a YCS or SSAT user of GIAS
WHEN viewing tools
THEN I have access to Bulk update governance
=> Updated authorised roles for YCS and 

Web/Edubase.Services/Governors/DisplayPolicies/GovernorDisplayPolicy.cs, Web/Edubase.Services/Governors/Models/GovernorModel.cs, Web/Edubase.Web.UI/Areas/Governors/Controllers/GovernorController.cs, Web/Edubase.Web.UI/Areas/Governors/Models/GovernorViewModel.cs, Web/Edubase.Web.UI/Views/Shared/EditorTemplates/GovernorViewModel.cshtml
Added recording of Original signatory member status to governance record for
Member – individual,
Member – organisation
For BO, YCS and SSAT user groups
https://dev.azure.com/dfe-ssp/s158-Get-Information-About-Schools/_workitems/edit/172669
=> Governance original signatory members

Web/Edubase.Web.UI/Assets/Scripts/Entry/add-edit-governor.js
Added JQuery to toggle dropdown/disable dropdown
https://dev.azure.com/dfe-ssp/s158-Get-Information-About-Schools/_workitems/edit/174529
When 'Original signatory member' is set to 'Yes', 'Appointing body' dropdown is set to N/A and is not editable.
=> Set default appointed body using JQuery function

Web/Edubase.Services/Governors/DisplayPolicies/GovernorDisplayPolicy.cs, Web/Edubase.Services/Governors/Models/GovernorModel.cs, Web/Edubase.Web.UI/Areas/Governors/Controllers/GovernorController.cs, Web/Edubase.Web.UI/Areas/Governors/Models/GovernorViewModel.cs, Web/Edubase.Web.UI/Views/Shared/EditorTemplates/GovernorViewModel.cshtml
Added recording of Original chair of trustees status to governance record for SSATs
For BO, YCS and SSAT user groups
https://dev.azure.com/dfe-ssp/s158-Get-Information-About-Schools/_workitems/edit/174527
=> Governance original chair of trustees

Web/Edubase.Web.UI/Areas/Governors/Controllers/GovernorController.cs, Web/Edubase.Web.UI/Areas/Governors/Models/GovernorViewModel.cs, Web/Edubase.Web.UI/Areas/Governors/Views/Governor/AddEditOrReplace.cshtml, Web/Edubase.Web.UI/Assets/Scripts/Entry/add-edit-governor.js, Web/Edubase.Web.UI/Views/Shared/EditorTemplates/GovernorViewModel.cshtml
Added new appointingbodyiddropdown element id to allow saving of selection.
Added original signatory member/original chair of trustees check for 'Yes' when group->governance edit page is loaded.
=> SSAT Governance - JQuery update to auto select 'Appointing body'

Web/Edubase.Web.UI/Areas/Groups/Models/Validators/GroupEditorViewModelValidator.cs, Web/Edubase.Web.UI/Areas/Groups/ViewRulesHandlers/GroupEditorViewModelRulesHandler.cs, Web/Edubase.Web.UI/Areas/Groups/Views/Group/EditDetails.cshtml, Web/Edubase.Web.UI/Helpers/FormHelpers.cs
Reverts DFE-Digital/get-information-about-schools#448
=> Revert "Bg/174545 1619 closed created in error"

azure-pipelines.yml, pipelines/smokeTestWebUi.ps1, pipelines/template-build-and-test.yml, pipelines/template-deployment-stage.yml, pipelines/template-smoke-test-deployment.yml
_Work-in-progress_ to migrate deployment pipelines to new ADO organisation.
AB#178569
**Build, test, and package**
**Dev**
**Test**
**Pre-Production**
**Production**
=> Set up CI with Azure Pipelines

Web/Edubase.Web.UI/Areas/Groups/Views/Group/_EditLayoutPage.cshtml
Updated group edit layout page to show governance tab for SSAT
https://dev.azure.com/dfe-ssp/s158-Get-Information-About-Schools/_workitems/edit/179004
=> Updated group edit layout page to show governance tab for SSAT

Web/Edubase.Web.UI/Areas/Governors/Views/Governor/ViewEdit.cshtml
As produced during group coding/debugging session.
The issue is that the edit/remove/replace buttons were not displaying.
```
CURRENT: 
// if has full access
// ... and if user can view edit button (`Model.GovernorPermissions.Update`)
// ... ... show edit button
// ... and if user can view remove/replace button (`Model.GovernorPermissions.Remove`)
// ... ... show remove button
PROPOSED: 
// if (has full access) OR ( (can view edit button) OR (can view replace/replace button) )
// ... and if user can view edit button (`Model.GovernorPermissions.Update`)
// ... ... show edit button
// ... and if user can view remove/replace button (`Model.GovernorPermissions.Remove`)
// ... ... show remove button
```
=> Editing individual governors

Web/Edubase.Web.UI/Web.config
Initial commit - Removed child-src - added: worker-src
=> Initial commit - Removed child-src - added: worker-src

Web/Edubase.Web.UI/Controllers/FaqController.cs
removed ValidateAntiForgeryToken from get request
created a new branch as original is too old
=> removed ValidateAntiForgeryToken from get request

Web/Edubase.Services/IntegrationEndPoints/AzureMaps/AzureMapsService.cs, Web/Edubase.Services/IntegrationEndPoints/OSPlaces/OSPlacesApiService.cs, Web/Edubase.Services/IntegrationEndPoints/PollyUtil.cs, Web/Edubase.ServicesUnitTests/IntegrationEndPoints/PollyUtilTests.cs, Web/Edubase.Web.UI/Web.config
Create disable feature for retries as well as creating a value we can change for timeouts
=> BG/191418 - Create disable feature for retries as well as creating a value we can change for timeouts

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/TabLocation.cshtml
UPRN field visible on the locations tab of the establishments screen
=> Display UKPN field - BG/188944

Web/Edubase.ServicesUnitTests/IntegrationEndPoints/PollyUtilTests.cs
Change to original ticket for PollyUtilTests to allow additional time for delays on server
=> Bg/191418 retries timeouts_server_tests

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/TabLocation.cshtml
Commit to get correct UPRN with Full UPRN Name
=> 193264_Display name for UPRN is incorrect - change to Unique property reference number (UPRN) - and updated to correctly use UPRN

Web/Edubase.Services/Enums/EnumSets.cs, Web/Edubase.Services/Enums/eLookupGovernorRole.cs, Web/Edubase.Services/Governors/Factories/GovernorRoleNameFactory.cs
This PR prepares the frontend to be able to recognise the new "Governance professional to a secure SAT" role once it is implemented within the backend.
=> Governance professional to a secure SAT

Web/Edubase.Web.UI/Views/Notifications/EditBanner.cshtml
Character count missing in notification banner
=> Bg/193462 Character count is missing

Web/Edubase.ServicesUnitTests/IntegrationEndPoints/PollyUtilTests.cs
Restored branch to modify the polyUtil unit test
=> BG/193913 - Shared governance pro to Group/Establishment_RestoredBranch

Web/Edubase.Web.UI/Areas/Governors/Views/Governor/ViewEdit.cshtml
reverted id of button to old value because js was looking for this id
=> js code is looking for an id of remove-shared-governor

Web/Edubase.ServicesUnitTests/IntegrationEndPoints/PollyUtilTests.cs
Royal Cypher ticket with commented out test to resolve pipeline issue - new ticket being created to resolve test
=> 196311 royal cypher update with test fix

Web/Edubase.Web.UI/Areas/Governors/Models/GovernorsGridViewModel.cs
Historic title display for Shared Governance Professional (establishment)
=> Historic title display for Shared Governance Professional (establishment)

Web/Edubase.Web.Resources/ApiMessages.resx, Web/Edubase.Web.UI/Areas/Governors/Controllers/GovernorController.cs, Web/Edubase.Web.UI/Views/Shared/EditorTemplates/DateTimeViewModel.cshtml
Change error message to message coming from Java -Also takes care of duplicate error:
There is a duplicate error message that is currently being handled with a distinct() call, this ticket is to stop the need for this by preventing the additional error message
=> Bg/bug 199191 Incorrect message

Web/Edubase.Web.UI/App_Start/IocConfig.cs, Web/Edubase.Web.UI/Areas/Governors/Models/GovernorsGridViewModel.cs, Web/Edubase.Web.UI/Areas/Groups/Controllers/GroupController.cs, Web/Edubase.Web.UI/Controllers/SearchController.cs, Web/Edubase.Web.UI/Helpers/HtmlHelperExtensions.cs
1 - Security issue: timeout to limit execution time
2 - Duplicated string literals
=> 204691 - Sonarcloud issues

Web/Edubase.Web.UI/Areas/Governors/Controllers/SharedGovernorController.cs
Note that any failures are _currently_ silently hidden, and a "success" page/message is displayed regardless (despite the change not being accepted or taking effect).
#204489
=> Show error messages where updating a shared governor's details fails.

Web/Edubase.Web.UI/Assets/Scripts/GiasSearchForm/autocomplete-setup.js
Add debouncing to search suggestions
=> BG/198726 Add debouncing to search suggestions 

Web/Edubase.Web.UI/Assets/Scripts/GiasSearchFilters/GiasFiltering.js
Show error message when there is a problem requesting either a search filter token or the results for that search filter token.
#210658
=> Show error message when there is a problem searching

Web/Edubase.Web.UI/Assets/Scripts/GiasSearchFilters/GiasFiltering.js
Provide a message with the infinite swirl after 5 seconds, to ask the user to 'please wait'
=> BG/206466 Waiting Message

Web/Edubase.Services/Edubase.Services.csproj, Web/Edubase.Services/ExternalLookup/FBService.cs, Web/Edubase.Services/ExternalLookup/FSCPService.cs, Web/Edubase.Services/IntegrationEndPoints/AzureMaps/AzureMapsService.cs, Web/Edubase.Services/IntegrationEndPoints/OSPlaces/OSPlacesApiService.cs, Web/Edubase.Services/IntegrationEndPoints/PollyUtil.cs, Web/Edubase.Services/packages.config, Web/Edubase.ServicesUnitTests/Edubase.ServicesUnitTests.csproj, Web/Edubase.ServicesUnitTests/IntegrationEndPoints/PollyUtilTests.cs
=> Polly update with Vue changes

Web/Edubase.Web.UI/Areas/Governors/Models/GovernorsGridViewModel.cs
=> Fix bug in displaying the "shared with" data for shared governance professionals.

Web/Edubase.Web.UI/Assets/Scripts/Entry/download-select-fields.js
=> Fix typo on download select fields page

Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Index.cshtml
Reverts DFE-Digital/get-information-about-schools#627
=> Revert "Bg/240388 rating field visibility"

Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Index.cshtml
Field Visibility, reverted from Dev to add to sandbox1
=> Field Visibility

Web/Edubase.Data/Repositories/WebLogItemRepository.cs
=> 247449 server error is throwing in prod environment when view logs from tools tab is selected

Web/Edubase.Data/Repositories/WebLogItemRepository.cs
=> ab#247449 view logs server error

Web/Edubase.Web.UI/Views/Shared/EditorTemplates/GovernorViewModel.cshtml
=> added new static text

Web/Edubase.Web.UI/Controllers/DownloadsController.cs, Web/Edubase.Web.UI/Models/Search/DownloadErrorViewModel.cs, Web/Edubase.Web.UI/Views/Shared/Downloads/DownloadError.cshtml, Web/Edubase.Web.UIUnitTests/Controllers/DownloadsControllerTests.cs
Unit tests to cover RequestScheduledExtract
=> 247448 - Failed_Extracts

Web/Edubase.Web.UI/Areas/Establishments/Controllers/EstablishmentController.cs, Web/Edubase.Web.UI/Areas/Groups/Controllers/GroupController.cs, Web/Edubase.Web.UI/Areas/Groups/Models/GroupDetailViewModel.cs, Web/Edubase.Web.UI/Models/EstablishmentDetailViewModel.cs, Web/Edubase.Web.UIUnitTests/Areas/Groups/Controllers/GroupControllerTests.cs
Reverts DFE-Digital/get-information-about-schools#696
=> Revert "BG/256758 StaticLinks"

Web/Edubase.Web.UI/Views/Guidance/EstablishmentBulkUpdate.cshtml
=> Bulk Establishment Documentation

Web/Edubase.Services/Establishments/Models/IEBTModel.cs, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/Header.cshtml, Web/Edubase.Web.UI/Models/EstablishmentDetailViewModel.cs
Initial commit to take method out of the IEBTModel - pending a change by backend
=> BG/Changes for Java

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/Header.cshtml
=> BG/267467 SCE only

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/Header.cshtml
=> BG/268997 Duplicate links

Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Downloads/SelectCustomFields.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/EstablishmentsSearch/Downloads/SelectDataset.cshtml, Web/Edubase.Web.UI/Views/Shared/Downloads/SelectFormat.cshtml
=> BG/268004 Specific search
