DFE-Digital/get-information-about-schools

Web/Edubase.Web.UI/403.html, Web/Edubase.Web.UI/404.html
Two of the static pages had an obsolete link to the contact section, this has been updated.
=> 47899-update-target-links-two-pages

Web/Edubase.Web.UI/App_Code/helpers.cshtml, Web/Edubase.Web.UI/Assets/Scripts/GiasGlobal/GiasAccordionExtensions.js, Web/Edubase.Web.UI/Views/GOVUK/Layouts/template.cshtml
tweaked both the helper and the accordion so that all "back to top" links go to a "top" anchor on the body element (taking the user to the true top of the page as per the example on GDS)
=> 48089 - added top id to body and tweaked back-to-top links

Web/Edubase.Web.UI/Areas/Establishments/Controllers/EstablishmentController.cs, Web/Edubase.Web.UI/Areas/Establishments/Models/CreateEstablishmentViewModel.cs, Web/Edubase.Web.UI/Areas/Establishments/Models/Validators/CreateEstablishmentViewModelValidator.cs, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Create.cshtml
Updated journey to allow backlinks to take user to previous screens rather than all the way out to the tools page. To ensure this worked as required there are now three components which get updated with each page build to reference the previous step, the active (current) step, and the point in the journey the user should be directed to upon a successful postback.
To ensure that there no obsolete fields remain populated if the user changes their mind mid-journey, there are also some conditional elements around the hidden fields depending on at which stage the user is at.
=> 49440 back links

Web/.nuget/NuGet.config
- `Nuget.config` references a private/authenticated/internal nuget feed named `DM Common`
- Usages of the IP Blacklisting functionality of `DM.Common` was removed within PR #220 / agilefactory 53908
- The only remaining reference to `DM.Common` is to this feed
- Automated build and tests pass without the `.nuget` directory at all, and initial manual tests indicate it runs locally fine
- Remove references to the now-unused privated/authenticated/internal nuget feed named `DM Common` from `NuGet.config
- Remove the also-unused `disableSourceControlIntegration` setting (used by [Team Foundation Version Control](https://learn.microsoft.com/en-us/nuget/consume-packages/packages-and-source-control#omitting-packages-with-team-foundation-version-control) which isn't in use for this project)
- ... …
=> Remove remaining references to `DM.Common`

Web/Edubase.Web.Resources/ApiMessages.resx
#138964
Note that this updated error message specifically uses the `Date appointment ended` terminology from the UED. 
A separate commit/PR to follow re: updating the field name within the form field's label.
**Before:**
- <img width="391" alt="image" src="https://user-images.githubusercontent.com/96429508/214969460-a151233f-aad2-4b53-ac5d-032ac033177f.png">
- <img width="283" alt="image" src="https://user-images.githubusercontent.com/96429508/214969509-a2df6cec-1c83-45a7-b0c9-d388f0b85ca2.png">
**After:**
- <img width="503" alt="image" src="https://user-images.githubusercontent.com/96429508/214969889-06bfc8a6-151b-4481-a7f5-847c73461522.png">
- <img width="273" alt="image" src="https://user-images.githubusercontent.com/96429508/214970000-34acdff0-fe73-4d7e-a01b-07a398d1651a.png">
=> Amend error message when the date an appointment ends, is before the appointment starts

Web/Edubase.Services/Enums/EnumSets.cs, Web/Edubase.ServicesUnitTests/EnumSetTests.cs
The collection now matches the database and the listed description.
Proposed changes/edits:
- All six governance professional types listed
- Test cases validate this/prevent future accidental regressions
#140851
=> Add omitted governance professional to enumset

Web/Edubase.Services/Enums/EnumSets.cs, Web/Edubase.Web.UI/Areas/Governors/Controllers/GovernorController.cs, Web/Edubase.Web.UIUnitTests/Areas/Governors/Controllers/GovernorControllerTests.cs
- There is pre-existing functionality to prevent creating a new chair of a local governing body where it (or the shared equivalent) already exists
- Extend pre-existing functionality/behaviour to also apply validation rules permitting only a single appointment of any type of governance professional
**Creating as draft PR for now as unclear if this is to be implemented within frontend/backend(/both).**
=> Restrict creating new if would overlap with current governance professional

Web/Edubase.Web.UI/Areas/Governors/Models/GovernorsGridViewModel.cs
This makes it spelled out for public and non-public pages, consistent with prior work to spell it out for only governance professionals.
#135249
=> Rename GID for remaining governance roles

Web/Edubase.Web.UI/Areas/Governors/Views/Governor/ViewEdit.cshtml
The GID did not change when coming from DB so this has been updated - and the full name has been used:
Governance role identifier (GID) and not Governor role identifier (GID)
=> Bg additional changes for 132800

Web/Edubase.Web.UI/Areas/Establishments/Views/AcademyOpenings/Index.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/AcademyOpenings/SearchAcademyOpenings.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Details.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/GovernanceChangeHistory.cshtml, Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/_EditLayoutPage.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Details.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/GovernanceChangeHistory.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/_EditLayoutPage.cshtml, Web/Edubase.Web.UI/Views/Downloads/Index.cshtml
tab-wrap and opening tables had same ids so it fails accessibility. To avoid it, just updated them with unique ids
=> updated Tab-wrap and opening tables as unique ids.

Web/Edubase.Services/Enums/eLookupGroupType.cs, Web/Edubase.Web.UI/Areas/Groups/Controllers/GroupController.cs, Web/Edubase.Web.UI/Areas/Groups/Models/CreateEdit/CreateAcademyTrustViewModel.cs, Web/Edubase.Web.UI/Areas/Groups/Models/CreateEdit/SearchCompaniesHouseModel.cs, Web/Edubase.Web.UI/Areas/Groups/Views/Group/CreateAcademyTrust.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Details.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/SearchCompaniesHouse.cshtml, Web/Edubase.Web.UI/Controllers/ToolsController.cs, Web/Edubase.Web.UI/Models/ToolsViewModel.cs, Web/Edubase.Web.UIUnitTests/Areas/Groups/Controllers/GroupControllerTests.cs
Uses a new link on the 'tools' page to enable creation of a secure single-academy trust, if the user has permission to do so.
Introduced a academyTrustRoute parameter to the controller endpoints to track whether we're creating a secure academy trust, or a normal academy trust, to enable the re-use of the same code.
=> Secure 16 19 groups

Web/Edubase.Web.UI/Areas/Groups/Controllers/GroupController.cs, Web/Edubase.Web.UI/Areas/Groups/Views/Group/EditDetailsEmpty.cshtml, Web/Edubase.Web.UI/Edubase.Web.UI.csproj
Copy of behaviour from establishment details change handling to group details change handling, notifying the user where they have clicked save but there are no changes to be made (a change from current behaviour which continues and displays a green banner stating changes have been saved).
#141789
=> Notify users if they attempt to save a record, but have made nil changes

Web/Edubase.Web.UI/package.json
This change allows you to run `npm run-script buildDevWatch` 
This is identical to the pre-existing `npm run-script buildDev`, except it watches for any changes made to (e.g. JavaScript files) and automatically rebuilds without needing to manually re-run webpack.
=> Add npm script `buildDevWatch` to have webpack watch for changes and automatically re-compile/rebuild

Web/Edubase.Web.UI/Areas/Groups/Views/Group/Create.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/CreateChildrensCentre.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Details.cshtml, Web/Edubase.Web.UI/Areas/Groups/Views/Group/EditLinks.cshtml, Web/Edubase.Web.UI/Assets/Sass/GiasModules/GiasModals/_gias-content-modals.scss, Web/Edubase.Web.UI/Assets/Sass/main.scss
As the GIAS product manager, I need a pop-up message to appear when establishment users are creating a new federation to remind them that they need to update their establishment record governance details now that they are moving to become part of a federation so that all the establishments in the newly created federation have the same federation governance to reflect their new governing board.
[Update create a federation process to remind users to update establishment governance](https://dfe-ssp.visualstudio.com/s158-Get-Information-About-Schools/_workitems/edit/132810)
=> 132810 - Add popup reminder on federation creation

Web/.editorconfig, Web/Edubase.Web.UI/Global.asax.cs, Web/Edubase.Web.UI/Web.config
It's not perfect but this PR is progress toward adding documentation about each of the configuration options defined within `Web.config`.
Note that some defaults (e.g., URLs to non-production instances of 3rd party / other DfE APIs) has been removed from the `Web.config` file.
Developers relying on these defaults when running locally will need to add these values to `devsecrets.gias.config.alwaysignore` (i.e., if not already explicitly defining/overriding those values).
=> Add comments and documentation about configuration options within `Web.config`

Web/Edubase.Web.UI/Global.asax.cs
Add configuration option to supply a trusted SHA1 SSL certificate thumbprint
(e.g., for a self-signed certificate used with a locally-running API server)
This replaces the current manually-applied workaround/patch documented within the internal wiki.
To use, insert a configuration option within `devsecrets.gias.config.alwaysignore` alongside other local dev secrets. 
For example (note that spaces, punctuation, and case get normalised given that different tools present the SHA1 thumbprint in different formats):
```xml
```
=> Add configuration option to supply a trusted SHA1 SSL certificate thumbprint

Web/Edubase.Data/Entity/DataQualityStatus.cs, Web/Edubase.Services/Security/EdubaseRoles.cs, Web/Edubase.Web.UI/Controllers/DataQualityController.cs, Web/Edubase.Web.UIUnitTests/Controllers/DataQualityControllerTests.cs
the tools->View data owner teams' data status screen
has had the following entry added:
Establishment type: Secure academy 16-19 openers
Last updated:
Data owner: Youth Custody Service
Email: [SecureSchools.operations@justice.gov.uk](mailto:SecureSchools.operations@justice.gov.uk)
minimal code changes needed to display the establishment type string
[Devops story #146386](https://dfe-ssp.visualstudio.com/s158-Get-Information-About-Schools/_workitems/edit/146386)
=> show establishment type text in data owners table

Web/Edubase.Web.UI/Controllers/Api/UserRolesController.cs
YCS is a new user role - they are the data owner for secure 16-19 academies and therefore I've added them to the list of roles in UserRequiresDataQualityPrompt https://dfe-ssp.visualstudio.com/s158-Get-Information-About-Schools/_workitems/edit/149237
=> added YCS as a role requiring data owner popup

Web/Edubase.Web.UI/Web.config
**I've made modifications to this since getting approvals so I tried to reset the approvals but failed!**
Move back to getting lookups from the java API rather than the c# replacement API. The c# replacement API has not been released to production and we are adding functionality to the java lookups API for 16-19, hence going back to using that API for lookups.
This change is related to previous PRs https://github.com/DFE-Digital/get-information-about-schools/pull/237 and https://github.com/DFE-Digital/get-information-about-schools/pull/340 where the lookups API config was split out from the texuna API config to allow different APIs for each and the lookups API was pointed to the new c# replacement API
=> change config for lookups API

Web/Edubase.Web.UI/Controllers/DataQualityController.cs, Web/Edubase.Web.UI/Views/DataQuality/ViewStatus.cshtml
Fix to allow YCS users to update their last updated date as the data owner for secure academies
https://dfe-ssp.visualstudio.com/s158-Get-Information-About-Schools/_workitems/edit/148501
=> add YCS to list of AuthorisationRoles

Web/Edubase.Services.Texuna/Lookup/LookupApiService.cs, Web/Edubase.Services.TexunaUnitTests/Lookup/LookupApiServiceTests.cs, Web/Edubase.Services/Edubase.Services.csproj, Web/Edubase.Services/Lookup/IUserDependentLookupService.cs, Web/Edubase.Web.UI/App_Start/IocConfig.cs, Web/Edubase.Web.UI/Areas/Establishments/Controllers/EstablishmentController.cs, Web/Edubase.Web.UIUnitTests/Areas/Establishments/Controllers/EstablishmentControllerTests.cs, Web/Edubase.Web.UIUnitTests/MockHelper.cs
The API lookup service has been modified to return values for the establishment status dropdown dependent on the user.
Changes to FE code to use the lookup directly, avoiding the caching, because the caching doesn't cache by user (now I'm writing this though I wonder if I could have implemented caching per user)
=> new lookup service for lookups based on user

Web/Edubase.Web.UI/Controllers/DownloadsController.cs, Web/Edubase.Web.UI/Models/ToolsViewModel.cs, Web/Edubase.Web.UI/Views/Tools/DownloadClosedTrustsInformation.cshtml
FE work - text changes to show that the report now includes secure 16-19 academy trusts
https://dfe-ssp.visualstudio.com/s158-Get-Information-About-Schools/_workitems/edit/146409
=> content changes to show that SSATs appear in the trusts closure report

Web/Edubase.Services/Edubase.Services.csproj, Web/Edubase.Services/Enums/eLookupGovernorRole.cs, Web/Edubase.Services/Governors/Factories/GovernorRoleNameFactory.cs, Web/Edubase.ServicesUnitTests/Edubase.ServicesUnitTests.csproj, Web/Edubase.ServicesUnitTests/Governors/Factories/GovernorRoleNameFactoryTests.cs, Web/Edubase.ServicesUnitTests/Nomenclature/NomenclatureServiceTests.cs, Web/Edubase.Web.UI/Areas/Governors/Controllers/GovernorController.cs, Web/Edubase.Web.UI/Areas/Governors/Models/GovernorsGridViewModel.cs
Governance view - fix the naming of the governor roles on the views
Removes the conversion of an enum to a string - the current conversion code couldn't cope with the new governor role names having '-' e.g 'Member - indiviudal'
The nomenclature service method and associated tests aren't needed now - they're just there to show that I had the existing behaviour covered by tests before I replaced the code. Not sure what to do about that - maybe another PR to remove the unwanted code afterwards.
https://dfe-ssp.visualstudio.com/s158-Get-Information-About-Schools/_workitems/edit/145544
=> 16 19 secure/145544 governance view

Web/Edubase.Services/Governors/Search/GovernorSearchPayload.cs, Web/Edubase.Services/Governors/Search/eGovernorTypesFlag.cs, Web/Edubase.Web.UI/Areas/Governors/Models/GovernorSearchViewModel.cs
This adds filtering by Secure SAT as an option when searching for governors. The corresponding backend change is in place and manual tests locally confirm this to be working.
#164278
=> Add Secure SAT as a filter option when searching for governors

Web/Edubase.Web.UI/App_Start/StartupSecureAccess.cs, Web/Edubase.Web.UI/Web.config
Add configuration option for `PublicOrigin`, to allow redirects to a proxy/WAF URL different to the server's application URL.
#157607 #171878
=> Update to allow DSI to work with GIAS behind proxy/WAF

.github/workflows/build-and-test.yml
This pull request adds SonarCloud analysis to the repository, including te 
st coverage analysis.
As part of this, once analysis of a pull request is done, a new comment will appear indicating details about the code changed within that pull request as compared to the branch being merged into.
For reference: 
- Project added to SonarCloud
- New repository secret `SONAR_CLOUD` added to this repo
- Settings changed on SonarCloud:
- "Automatic analysis": disabled 
- (GitHub Actions will push data to SonarCloud, as opposed to SonarCloud periodically polling for updates/changes)
- New Code: Previous version
- Long-lived branches pattern: `(branch|release|dev|epic|master|main).*`
All other settings are the defaults, and may need to be refined as we gain experience with SonarCloud (e.g., quality …
=> Add SonarCloud analysis

azure-pipelines.yml, pipelines/template-build-and-test.yml
Nuget dependency caching issues is causing problems since merging into dev and unable to immediately resolve, so this PR is removing caching to allow pipeline runs to progress We can re-add this optimisation back later.
=> Remove nuget caching

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/Header.cshtml, Web/Edubase.Web.UI/Areas/Groups/Models/GroupDetailViewModel.cs, Web/Edubase.Web.UI/Areas/Groups/Views/Group/Details.cshtml, Web/Edubase.Web.UI/Models/EstablishmentDetailViewModel.cs, Web/Edubase.Web.UI/Models/HomepageViewModel.cs, Web/Edubase.Web.UI/Views/Guidance/General.cshtml, Web/Edubase.Web.UI/Views/Home/Index.cshtml, Web/Edubase.Web.UI/Views/Home/Responsibilities.cshtml, Web/Edubase.Web.UI/Web.config
This PR introduces a configurable service name for FSCPD/CSCP (following renames), defaulting to the new CSCP name. 
This configurable service name is currently used only on the establishment and group details pages for now, while clarification about the home page and help page is being sought.
=> Configurable FSCPD service name

Web/Edubase.Data/Edubase.Data.csproj, Web/Edubase.Data/Repositories/NotificationBannerRepository.cs, Web/Edubase.Web.UI/Controllers/NotificationsController.cs, Web/Edubase.Web.UI/Web.config
Edubase.Data.csproj - 
Automated code cleanup 
NotifiactionBannerRepository.cs -
Automated code cleanup
Constructor modified
2 new methods
GetNotificationBanners
GetActiveBanners
1 method removed
GetAll
Edit methods to banners clear the in memory cache to force an update on the instance - this wont do anything for other instances.
NotificationController.cs
Automated code cleanup
1 method modified - BannersPartial (last method in the file)
Web.Config
Automated code cleanup
One new setting added - NotificationBannerCacheExpirationInMinutes
Note on unit tests
It pains me to not have a unit test for this, but the NotifiactionBannerRepository inherits from a base class that has concrete dependencies that I cannot replace with Mocks without a lot of refactoring.
For the localised change and the …
=> 188811 / 190689 - notification banner thread issues

Web/Edubase.Services.Texuna/Core/HttpClientWrapper.cs, Web/Edubase.Web.UI/Web.config
If not provided or is empty string, defaults to pre-existing behaviour (no change).
See details / screenshots etc. within #189483
=> Add option to override x-source-ip

Web/Edubase.Services/Enums/EnumSets.cs, Web/Edubase.Services/Enums/eLookupGovernorRole.cs, Web/Edubase.Services/Governors/Factories/GovernorRoleNameFactory.cs
This commit prepares the frontend to be able to recognise the new "Governance professional for a single-academy trust (SAT)" role once it is implemented within the backend.
#191487
=> Governance professional to a SAT

Web/Edubase.Web.UI/Areas/Governors/Controllers/GovernorController.cs
Correct an error that appears when adding a 'Shared governance professional - group' and a 'Governance professional to a MAT'
=> BG/193913_add Shared governance professional to Group/Establishment level

azure-pipelines.yml
Update `smokeTestUrl` in Azure pipelines config to account for the new domain name for pre-prod (access to old URL blocked as that would bypass the WAF).
While doing this, I spotted the `/Downloads` part of the pre-prod/prod smoke test URLs was missing so I've fixed that too.
=> Update smokeTestUrl in Azure pipelines config to account for the new domain name for pre-prod 

Web/Edubase.ServicesUnitTests/ExternalLookup/FBServiceTests.cs, Web/Edubase.ServicesUnitTests/IntegrationEndPoints/PollyUtilTests.cs
Unit tests that are passing locally but then failing in the pipeline
1. PolyUtil - focus on directly testing timeout for a 'TimeoutRejectedException'
2. FBService - ensure configured correctly regardless of environmental variables
=> Bg/192355 Unit tests failing

Web/Edubase.Web.UIUnitTests/Areas/Governors/Controllers/GovernorControllerTests.cs
Remove previously allowed condition from PairwiseGovernanceProfessionalRolesAllowedCombinations - This will allow the condition to be tested in the: Gov_AddEditOrReplace_RoleSpecified_GovernanceProfessional_RoleAlreadyExists_DisallowedThereforeReject test method.
There are 2 combinations in an ignore list (in the GovernorControllerTests) - currently the test passes, as these combinations are not being tested (ignored)
However...these shouldn't be in the ignore list.
When they are taken out, and the test properly checks them, they pass successfully - ticket just to move into current place.
=> Bg/212981 Remove previously allowed condition from PairwiseGovernanceProfessionalRolesAllowedCombinations

Web/Edubase.Web.UI/Assets/Scripts/GiasSearchFilters/GiasFiltering.js
The friendly message has been changed to: 
'Continue to wait while we load the search results.'
=> Bg/206466 New change to friendly message

Web/Edubase.Web.UI/Controllers/ToolsController.cs, Web/Edubase.Web.UI/Models/ToolsViewModel.cs
Update visual display of the logs/caches links on the tools page - only if a backoffice user.
Note this is just visual display of the link - accessing the pages is already denied/prevented.
#208253
=> Update visual display of the logs/caches links on the tools page - only if a backoffice user.

Web/Edubase.Web.UI/Areas/Governors/Controllers/GovernorController.cs, Web/Edubase.Web.UI/Areas/Governors/Views/Governor/ViewEdit.cshtml
Where we deny the user creating a new governance role record because a person in that role already exists (e.g., chair of trustees, accounting officer, and the new governance professional roles), the drop-down box currently defaults to whichever entry is top of the list.
During governance professional testing, it is felt this is misleading as it initially looks like whatever value is first in the list already has an appointee.
Additionally, WCAG 2.2 requires form fields to not be cleared when validating user input.
https://design-system.service.gov.uk/patterns/validation/#wcag-edit-to-correct-errors
For this reason, this PR has a basic implementation which causes the drop-down to pre-select whichever role the user submitted.
=> Do not clear gov role on error

Web/Edubase.Services.Texuna/Governors/GovernorsReadApiService.cs, Web/Edubase.Web.UI/App_Start/IocConfig.cs, Web/Edubase.Web.UI/Web.config
Governor search is extremely poorly performing currently, and a quick-win broad increase to the general HTTP client timeout previously allowed the site to continue functioning. Future work may improve the performance of this API but in the meanwhile we feel it would be helpful to have a more targeted increase to the timeout.
This PR introduces a new HTTP client specifically for the governor search API query, to allow for a narrowly-defined increased timeout specifically for this only.
(currently the increased timeout workaround applies generically to all the default HttpClient requests)
Note that this change is backwards compatible, by defaulting back to the generic Texuna Java API connection details/credentials if the more-specific (governor-search) details/credentials are not provided …
=> 215376  governor search timeout

Web/Edubase.Web.UI/Areas/Governors/Views/Governor/ViewEdit.cshtml
Currently, in some circumstances where there are no governance roles available/permitted to be added to an establishment/group, we display an empty drop-down list and this has led to some confusion.
This PR, instead, shows a textual explanation/description that there are no governance roles available.
#203275
=> Show a textual explanation/description that there are no governance roles available, instead of an empty drop-down select list.

Web/Edubase.Web.UI/Views/Shared/EditorTemplates/GovernorViewModel.cshtml
Currently these fields are styled as a `govuk-input` (while behaving as a select/drop-down).
This PR fixes the the `govuk` class to correctly style these fields as a select/dropdown, by using `govuk-select` instead of `govuk-input`.
- **BEFORE**: 
- ![image](https://github.com/user-attachments/assets/50fb4118-05e5-41b8-adeb-8d4e63289fb6)
- ![image](https://github.com/user-attachments/assets/b2c409dd-3725-4e6f-b8f9-e9aea3d53457)
- **AFTER**: 
- ![image](https://github.com/user-attachments/assets/1af27238-2e97-41de-8dd5-ad52bca71f4a)
- ![image](https://github.com/user-attachments/assets/7c1e01b5-f30b-4c0f-889c-4abfeda10469)
=> Trivial fix, for display of original signatory member/chair of trustees

Web/Edubase.Services/Governors/Factories/GovernorRoleNameFactory.cs, Web/Edubase.ServicesUnitTests/Governors/Factories/GovernorRoleNameFactoryTests.cs
During UAT the naming requirements changed for governance professionals. This PR implements those naming changes.
=> Reflect new governance professional role name requirements (following UAT) #230908

Web/Edubase.Web.UI/Areas/Governors/Controllers/SharedGovernorController.cs, Web/Edubase.Web.UI/Areas/Governors/Models/Validators/SelectSharedGovernorViewModelValidator.cs, Web/Edubase.Web.UI/Assets/Scripts/GiasGlobal/GiasReOrderValidationSummary.js, Web/Edubase.Web.UI/Views/Shared/EditorTemplates/DateTimeViewModel.cshtml, Web/Edubase.Web.UI/Views/Shared/_ValidationSummary.cshtml, Web/Edubase.Web.UIUnitTests/Areas/Governors/Models/SelectSharedGovernorViewModelValidatorTests.cs, Web/Edubase.Web.UIUnitTests/Edubase.Web.UIUnitTests.csproj
Per UAT, the end date is now optional for this role.
- **Requirements that the _shared governance professional - establishment_ should have an optional end date:**
- ![image](https://github.com/user-attachments/assets/4e59a397-6596-45f9-ae57-180a04124ff8)
- **Confirmation that the Java API will accept the submission (i.e., this is a frontend validation only):**
- ![image](https://github.com/user-attachments/assets/41aac585-37b3-469c-a2ec-53962e813446)
- **Note that error messages coming from the Java API are handled separately/differently, and do not get linked (data being submitted to the API means the C# validations have passed):**
- ![image](https://github.com/user-attachments/assets/63e2fa20-5033-4feb-b2d8-6bf21a129ab3)
Note that this PR includes some additional fixes while I was …
=> End date for 'shared governance professional - establishment' is now optional, per UAT

Web/Edubase.Web.UI/Views/Guidance/EstablishmentBulkUpdate.cshtml, Web/Edubase.Web.UI/Web.config
**Background**
Per recent changes within Ofsted, inspection results are moving away from a single rating to a different system.
While this is being finalised, we will no longer accept updates to Ofsted-related fields via bulk-update. As a result, these fields will be removed from the guidance.
**Changes made**
- This pull request introduces a feature toggle, to optionally hide/show Ofsted-related fields from the bulk-update guidance
- The default setting is to continue displaying it (current behaviour)
**"Show, don't tell"**
- Feature toggle on (left) / off (right):
- ![image](https://github.com/user-attachments/assets/b261c2d6-e968-4224-bed1-a5a59b734b48)
- ![image](https://github.com/user-attachments/assets/f0fc80da-39bc-464d-8ff2-89b270a63f43)
=> Hide the Ofsted fields from the bulk update guidance.

Web/Edubase.Web.UI/Areas/Establishments/Views/Establishment/Partials/Header.cshtml
#232329
The details section text is as-provided. 
Note that without the margin override, the link to the report and the clickable details link are too close together.
=> Add a "details" section explaining why GIAS no longer displays Ofsted ratings
